_extends: .github

repository:
  name: gitcord-forum
  description: "A middleware designed to sort your repository feeds into Discord forum posts. Built with Cloudflare Workers"
  private: false
  topics: "discord, discord-bot, discord-rest, cloudflare, cf-worker, cf-workers, cloudflare-worker, cloudflare-workers, middleware"

branches:
  - name: main
    protection:
      required_status_checks:
        checks:
          - context: Test build
          - context: ESLint
          - context: DeepScan
          - context: CodeQL
